name: Java Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    cron: '0, 12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js v20.16.0
        uses: actions/setup-node@v4
          cache: maven 

      - name: Run audit
        run: npm run audit
        